# Define the name of the workflow
name: CI/CD Pipeline

# Define the trigger for the workflow
on:
  push:
    branches: [main]

# Define the jobs that will be executed
jobs:
  build:
    runs-on: ubuntu-latest # Use an Ubuntu instance for running the job

    steps:
    # Step 1: Check out the latest code changes
    - uses: actions/checkout@v2 # Use the GitHub Actions checkout action
    # Step 2: Install Node.js
    - name: Install Node.js
      uses: actions/setup-node@v2 # Use the GitHub Actions setup-node action
      with:
        node-version: 14 # Specify the version of Node.js to install
    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci # Install dependencies using npm ci
    # Step 4: Lint and test code
    - name: Lint and test code
      run: npm run lint && npm run test # Run linting and testing scripts using npm run lint and npm run test
    # Step 5: Build the project
    - name: Build the project
      run: npm run build # Build the project using npm run build
    # Step 6: Deploy to EC2 instance
    - name: Deploy to EC2 instance
      run: |
        # Use SSH to connect to the EC2 instance and execute deployment commands
        ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-instance-ip-address "cd /path/to/your/project && git pull origin main" # Pull the latest code changes from the repository
        ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-instance-ip-address "npm ci && pm2 restart server.js" # Install dependencies using npm ci and restart the server using PM2
